# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-02 21:25
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nzaa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boundary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('client', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('rights', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('received', 'received'), ('in work', 'in work'), ('complte', 'complete'), ('submitted', 'submitted'), ('hold', 'hold')], max_length=64)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=2193)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Record created at')),
                ('created_by', models.CharField(editable=False, max_length=255, verbose_name='Record created by')),
                ('modified', models.DateTimeField(auto_now=True, null=True, verbose_name='Record modified at')),
                ('modified_by', models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='Record modified by')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yourboundary', to=settings.AUTH_USER_MODEL)),
                ('visible_to', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
                'get_latest_by': 'created',
            },
        ),
    ]
