# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-07 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nzaa', '0002_boundary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='region',
            field=models.CharField(blank=True, choices=[(b'', b'---'), (b'otago', b'otago'), (b'taranaki', b'taranaki'), (b'canterburyregion', b'canterburyregion'), (b'tasmanregion', b'tasmanregion'), (b'aucklandregion', b'aucklandregion'), (b'nelsonregion', b'nelsonregion'), (b'northland', b'northland'), (b'waikatoregion', b'waikatoregion'), (b'gisborne', b'gisborne'), (b'manawatuwanganui', b'manawatuwanganui'), (b'southland', b'southland'), (b'hawkesbay', b'hawkesbay'), (b'westcoast', b'westcoast'), (b'marlboroughregion', b'marlboroughregion'), (b'bayofplentyregion', b'bayofplentyregion'), (b'wellingtonregion', b'wellingtonregion')], max_length=255, null=True, verbose_name='Region'),
        ),
        migrations.AlterField(
            model_name='site',
            name='tla',
            field=models.TextField(blank=True, choices=[(b'', b'---'), (b'manawatu', b'manawatu'), (b'hurunui', b'hurunui'), (b'whangarei', b'whangarei'), (b'otorohanga', b'otorohanga'), (b'southland', b'southland'), (b'lowerhutt', b'lowerhutt'), (b'rotorua', b'rotorua'), (b'kaipara', b'kaipara'), (b'mackenzie', b'mackenzie'), (b'stratford', b'stratford'), (b'southtaranaki', b'southtaranaki'), (b'opotiki', b'opotiki'), (b'southwairarapa', b'southwairarapa'), (b'queenstownlakes', b'queenstownlakes'), (b'waimakariri', b'waimakariri'), (b'westernbay', b'westernbay'), (b'auckland', b'auckland'), (b'wellingtoncity', b'wellingtoncity'), (b'outsideta', b'outsideta'), (b'tauranga', b'tauranga'), (b'carterton', b'carterton'), (b'hamilton', b'hamilton'), (b'rangatikei', b'rangatikei'), (b'gisborne', b'gisborne'), (b'whakatane', b'whakatane'), (b'timaru', b'timaru'), (b'kawerau', b'kawerau'), (b'tasmandistrict', b'tasmandistrict'), (b'waipa', b'waipa'), (b'horowhenua', b'horowhenua'), (b'kapiticoast', b'kapiticoast'), (b'ashburton', b'ashburton'), (b'porirua', b'porirua'), (b'invercargill', b'invercargill'), (b'westland', b'westland'), (b'waitomo', b'waitomo'), (b'waikatodistrict', b'waikatodistrict'), (b'ruapehu', b'ruapehu'), (b'whanganui', b'whanganui'), (b'chathamislands', b'chathamislands'), (b'clutha', b'clutha'), (b'kaikoura', b'kaikoura'), (b'farnorth', b'farnorth'), (b'wairoa', b'wairoa'), (b'waitaki', b'waitaki'), (b'buller', b'buller'), (b'waimate', b'waimate'), (b'taupo', b'taupo'), (b'selwyn', b'selwyn'), (b'masterton', b'masterton'), (b'newplymouth', b'newplymouth'), (b'tcdc', b'tcdc'), (b'grey', b'grey'), (b'hauraki', b'hauraki'), (b'southwaikato', b'southwaikato'), (b'tararua', b'tararua'), (b'nelson', b'nelson'), (b'christchurch', b'christchurch'), (b'matamatapiako', b'matamatapiako'), (b'centralhawkesbay', b'centralhawkesbay'), (b'centralotago', b'centralotago'), (b'upperhutt', b'upperhutt'), (b'hastings', b'hastings'), (b'dunedin', b'dunedin'), (b'marlboroughdistrict', b'marlboroughdistrict'), (b'gore', b'gore')], null=True, verbose_name='Territorial authority'),
        ),
    ]
