# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-31 01:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, choices=[('blog_personal', 'personal blog'), ('blog_work', 'professional blog'), ('email', 'email'), ('email_private', 'private email'), ('email_work', 'work email'), ('fax', 'fax'), ('phone_home', 'home phone'), ('phone_mob', 'mobile phone'), ('phone_office', 'office phone'), ('postal', 'postal address'), ('street', 'street address'), ('website', 'website')], max_length=255, null=True)),
                ('data', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('number', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('initial', models.CharField(blank=True, max_length=16, null=True, unique=True)),
                ('nickname', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('affiliation', models.CharField(blank=True, max_length=255, null=True)),
                ('interests', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Record created at')),
                ('created_by', models.CharField(editable=False, max_length=255, verbose_name='Record created by')),
                ('modified', models.DateTimeField(auto_now=True, null=True, verbose_name='Record modified at')),
                ('modified_by', models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='Record modified by')),
            ],
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('provenance', models.TextField(blank=True, editable=False, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Record created at')),
                ('created_by', models.CharField(editable=False, max_length=255, verbose_name='Record created by')),
                ('modified', models.DateTimeField(auto_now=True, null=True, verbose_name='Record modified at')),
                ('modified_by', models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='Record modified by')),
                ('name_short', models.CharField(blank=True, max_length=255, null=True)),
                ('name_long', models.CharField(blank=True, max_length=255, null=True)),
                ('industry', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.ManyToManyField(blank=True, to='members.Address')),
            ],
            options={
                'ordering': ('name_short',),
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('provenance', models.TextField(blank=True, editable=False, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Record created at')),
                ('created_by', models.CharField(editable=False, max_length=255, verbose_name='Record created by')),
                ('modified', models.DateTimeField(auto_now=True, null=True, verbose_name='Record modified at')),
                ('modified_by', models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='Record modified by')),
                ('name_first', models.CharField(blank=True, max_length=255, null=True)),
                ('name_last', models.CharField(blank=True, max_length=255, null=True)),
                ('initials', models.CharField(blank=True, max_length=255, null=True)),
                ('nickname', models.CharField(blank=True, max_length=255, null=True)),
                ('citation', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.ManyToManyField(blank=True, to='members.Address')),
                ('organisation', models.ManyToManyField(blank=True, to='members.Organisation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='member',
            name='person',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.Person'),
        ),
        migrations.AddField(
            model_name='member',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
