# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-02 18:32
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boundary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('client', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=2193)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Record created at')),
                ('created_by', models.CharField(editable=False, max_length=255, verbose_name='Record created by')),
                ('modified', models.DateTimeField(auto_now=True, null=True, verbose_name='Record modified at')),
                ('modified_by', models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='Record modified by')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.Member')),
            ],
        ),
    ]
