# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-02 21:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_boundary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boundary',
            name='member',
        ),
        migrations.DeleteModel(
            name='Boundary',
        ),
    ]
