# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-10-17 22:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_auto_20190203_1025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisation',
            name='address',
        ),
        migrations.RemoveField(
            model_name='person',
            name='address',
        ),
        migrations.RemoveField(
            model_name='person',
            name='organisation',
        ),
        migrations.RemoveField(
            model_name='member',
            name='person',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='Organisation',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
