"""Functions to map fields from source for import into the local system.

Returns values for site type, subtype, ethnicity and period based on
input data from the source. Operates a series of conditionals on
various values mainly in the short_desc field.

Functions in this module consume dictionary objects generated by the
Scrape method process_extract().

The specific fields it expects are:

    name, short_desc, type,

The module-level structures compare lowercase values in input fields
to returnable values in a tuple:

The returns from each of the functions are:

    ethnicity_map        ethnicity
    period_map           period
    type_map             (site_type, site_subtype)

"""

ethnicity_map = {
    'Combination': "",
    'Maori': "Maori",
    'Non Maori': "",
    'anti aircraft': 'Modern NZ',
    'anti-aircraft': 'Modern NZ',
    'chinese': 'Chinese',
    'colonial': 'Colonial',
    'european': 'Colonial',
    'gunfighing pa': 'Maori',
    'gunfighter pa': 'Maori',
    'indigenous': 'Maori',
    'marae': 'Maori',
    'modern': 'Modern NZ',
    'urupa': 'Maori',
}

period_map = {
    'period': {
        'Indigenous pre-1769': 'Prehistoric',
        'Colonial 1840-1900': 'Colonial',
        'Contact 1769-1840': 'Contact',
        'Modern 1900-': 'Modern',
    },
    'short_desc': {
        'adit': 'Historic',
        "chinese": 'Historic',
        "taro": 'Prehistoric',
        "historic": 'Colonial, Historic',
        "gum digging": 'Historic',
        "source site": 'Prehistoric',
    },
}

type_map = {
    "Administrative": ('Administration', None),
    "Agricultural/ pastoral": ('Agricultural', None),
    "Art": ('Art', None),
    "Artefact find": ('Find spot', None),
    "Botanical evidence": ('Botanical', None),
    "Burial/ cemetery": ('Burial', None),
    "Canoe building": ('Industry', 'Canoe building'),
    "Cave/ rock shelter": ('Cave/rock shelter', None),
    "Cement/ lime works": ('Industry', 'Cement works'),
    "Commercial": ('Commerce', None),
    "Educational": ('Education', None),
    "Fishing": ('Fishing', None),
    "Flax milling": ('Industry', 'Flax milling'),
    "Flour milling": ('Industry', 'Flour milling'),
    "Gum digging": ('Gum digging', None),
    "Health care": ('Community', None),
    "Historic - domestic": ('Domestic', None),
    "Historic - land parcel": ('Administration', None),
    "Historic": ('',  None),
    "Hospital": ('Community', 'Hospital'),
    "Hulk": ('Maritime', 'Hulk'),
    "Industrial": ('Industry', None),
    "Maori horticulture": ('Maori horticulture', None),
    "Marae": ('Community', 'Marae'),
    "Memorial": ('Administration', 'Memorial'),
    "Midden/Oven": ('Midden/oven', None),
    "Military (non-Maori)": ('Military', None),
    "Mining - chromite": ('Mining', 'Chromite'),
    "Mining - coal": ('Mining', 'Coal'),
    "Mining - copper/ antimony": ('Mining', 'Copper'),
    "Mining - gold": ('Mining', 'Gold'),
    "Mining - tin": ('Mining', 'Tin'),
    "Mining": ('Mining', None),
    "Mission station": ('Mission station', None),
    "Pa - gunfighter": ('Pa', 'Gunfighter pa'),
    "Pa - island/ swamp": ('Pa', None),
    "Pa": ('Pa', None),
    "Pit/Terrace": ('Pit/terrace', None),
    "Power generation": ('Industry', 'Power plant'),
    "Recreation": ('Community', 'Recreation'),
    "Religious": ('Community', 'Church'),
    "Sealing camp": ('Whaling/sealing', 'Sealing camp'),
    "Shipwreck": ('Maritime', 'Shipwreck'),
    "Source site - argillite": ('Quarry', 'Argillite'),
    "Source site": ('Quarry', None),
    "Timber milling": ('Forestry', None),
    "Traditional site": ('Traditional site', None),
    "Transport/ communication": ('Transport/communication', None),
    "Unclassified": (None,  None),
    "Whaling Station": ('Whaling/sealing', 'Whaling station'),
    "Working area": ('Lithic working', None),
}

subtype_map = {

    'name': {
        "Bank": ('Commerce', 'Bank'),
        "Court house": ('Administration', 'Courthouse'),
        "Courthouse": ('Administration', 'Courthouse'),
        "Gaol": ('Administration', 'Prison'),
        "Government": ('Administration', 'Government'),
        "School": ('Education', 'School'),
        "Seamen's Institute": ('Community', 'Institute'),
        "post office": ('Administration', 'Post Office'),
    },

    'short_desc': {

        "a c camp": ('Administration', 'Armed Constabulary'),
        "ac ": ('Administration', 'Armed Constabulary'),
        "accommodation house": (None, 'Accommodation'),
        "adit": ('Mining', 'Adit'),
        "adze": (None, 'Adze'),
        "aerial tramway": ('Mining', 'Aerial way'),
        "anti aircraft": ('Military', 'Anit aircraft battery'),
        "anti-aircraft": ('Military', 'Anit aircraft battery'),
        "antimony": ('Mining', 'Antimony'),
        "aqueduct": (None, 'Aqueduct'),
        "argillite": (None, 'Argillite'),
        "bach": (None, ''),
        "bakehouse": ('Commerce', 'Bakery'),
        "baker": ('Commerce', 'Bakery'),
        "ballast": ('', 'Ballast'),
        "ballast": (None, 'Ballast'),
        "bank fence": ('Agricultural', 'Earthen fence'),
        "bark remov": ('Botanical', 'Scarred tree'),
        "battery": (None, 'Battery'),
        "blacksmith": (None, 'Blacksmith'),
        "bootmaker": ('Commerce', 'Bootmaker'),
        "borrow pit": ('Maori horticulture', 'Borrow pits'),
        "brewery": ('Industry', 'Brewery'),
        "brick kiln": ('Industry', 'Brickworks'),
        "brick oven": ('Industry', 'Brickworks'),
        "brick works": ('Industry', 'Brickworks'),
        "brickworks": ('Industry', 'Brickworks'),
        "cache": (None, 'Cache'),
        "cairn": ('Administration', 'Cairn'),
        "camp": (None, 'Camp'),
        "canoe building": ('Industry', 'Canoe building'),
        "canoe": (None, 'Canoe'),
        "carved rock": ('Art', 'Rock art'),
        "cave": ('Cave/rock shelter', 'Cave'),
        "cemetary": ('Burial', 'Cemetary'),
        "clearing": (None, 'Clearing'),
        "cob ": (None, 'Cob building'),
        "copper mine": ('Mining', 'Copper'),
        "cottage": (None, 'Cottage'),
        "cow shed": ('Agricultural', 'Cow shed'),
        "cowshed": ('Agricultural', 'Cow shed'),
        "cranium": ('Burial', 'Cranium'),
        "creamery": (None, 'Creamery'),
        "cultivation": (None, 'Cultivation'),
        "culvert": ('Transport/communication', ''),
        "culvert": (None, 'Culvert'),
        "dairy": ('Commerce', 'Dairy'),
        "dendroglyph": ('Art', 'Dendroglyph'),
        "ditch and bank": ('Agricultural', 'Earthen fence'),
        "drain": ('Agricultural', 'Drain'),
        "dressmaker": ('Commerce', 'Dressmaker'),
        "drive dam": ('Forestry', 'Driving dam'),
        "driving dam": ('Forestry', 'Driving dam'),
        "dwelling": (None, 'Dwelling'),
        "dynamo": (None, 'Power plant'),
        "earthwork fence": ('Agricultural', 'Earthen fence'),
        "eel": ('Fishing', 'Eel weir'),
        "factory": ('Industry', 'factory'),
        "farm house": ('Agricultural', 'Farm house'),
        "farmhouse": ('Agricultural', 'Farm house'),
        "fence line": ('Agricultural', 'Fence line'),
        "fence post": ('Agricultural', 'Fence Post'),
        "fencepost": ('Agricultural', 'Fence post'),
        "fire station": ('Administration', 'Fire service'),
        "fish trap": ('Fishing', 'Fish trap'),
        "fishtrap": ('Fishing', 'Fish trap'),
        "flake": (None, 'Flake'),
        "flax milling": ('Industry', 'Flax milling'),
        "flour milling": ('Industry', 'Flour milling'),
        "forge": (None, 'Forge'),
        "foundary": (None, 'Foundry'),
        "fruit tree": ('Botanical', 'Fruit trees'),
        "gasworks": ('Industry', 'Gasworks'),
        "generating": (None, 'Power plant'),
        "government": ('Administration', 'Government'),
        "grainstore": ('Commerce', 'Grain store'),
        "grave yard": ('Burial', 'Grave yard'),
        "graveyard": ('Burial', 'Grave yard'),
        "greenstone": (None, 'Greenstone'),
        "guest house": ('Commerce', 'Guest house'),
        "hall": ('Community', 'Hall'),
        "homestead": ('Agricultural', 'Homestead'),
        "hop kiln": ('Industry', 'Brewery'),
        "house": ('Agricultural', 'House'),
        "hut": (None, 'hut'),
        "hydro": ('Industry', 'Hydro power'),
        "jetty": ('Maritime', 'Jetty'),
        "kainga": ('Domestic', 'Kainga'),
        "karaka": ('Botanical', 'Karaka'),
        "kauri dam": ('Forestry', 'Driving dam'),
        "land parcel": ('Administration', 'Land parcel'),
        "lime burning": ('Industry', 'Lime kiln'),
        "lime kiln": ('Industry', 'Lime kiln'),
        "log dam": ('Forestry', 'Driving dam'),
        "logging": ('Forestry', None),
        "magazine": (None, 'Magazine'),
        "malt": ('Commerce', 'Malthouse'),
        "manganese": ('Mining', 'manganese'),
        "mercury": ('Mining', 'Mercury mine'),
        "mica": ('Mining', 'Mica mine'),
        "milking shed": ('Agricultural', 'Cow shed'),
        "mine": ('Mining', None),
        "mining": ('Mining', None),
        "moa bone": (None, 'Moa bone'),
        "mullock": ('Mining', 'Mullock'),
        "museum": ('Administration', ''),
        "mutilated tree": ('Botanical', 'Scarred tree'),
        "nephrite": (None, 'Greenstone'),
        "obsidian": (None, 'Obsidian'),
        "occupation": ('Domestic', 'Occupation'),
        "patuna": ('Fishing', 'Patuna'),
        "petroglyph": ('Art', 'Petroglyph'),
        "police": ('Administration', 'Police'),
        "portal": ('', ''),
        "post": (None, 'post'),
        "rabbit fence": ('Agricultural', 'Rabbit fence'),
        "rabbit proof fence": ('Agricultural', 'Rabbit fence'),
        "rail bridge": ('Transport/communication', 'Rail bridge'),
        "railway bridge": ('Transport/communication', 'Rail bridge'),
        "road": (None, 'Road'),
        "rock art": ('Art', 'Rock art'),
        "rock carving": ('Art', 'Rock art'),
        "rock drawing": ('Art', 'Rock art'),
        "rubbish": (None, 'Rubbish'),
        "saw mill": ('Forestry', 'Saw mill'),
        "sawing": ('Forestry', 'Saw mill'),
        "sawmill": ('Forestry', 'Saw mill'),
        "scarfed": ('Botanical', 'Scarred tree'),
        "scarp fence": ('Agricultural', 'Earthen fence'),
        "scarred tree": ('Botanical', 'Scarred tree'),
        "scheelite": ('Mining', 'Scheelite'),
        "school": ('Education', 'School'),
        "settlement": (None, 'settlement'),
        "shaft": (None, 'shaft'),
        "shearing shed": ('Agricultural', 'Shearing shed'),
        "shelter": (None, 'Shelter'),
        "ship build": ('Maritime', 'Shipyard'),
        "ship wreck": ('Maritime', 'Shipwreck'),
        "shipwreck": ('Maritime', 'Shipwreck'),
        "shipyard": ('Maritime', 'Shipyard'),
        "shop": ('Commerce', 'shop'),
        "skull": ('Burial', 'Cranium'),
        "skull": (None, 'Human remains'),
        "slipway": ('Maritime', 'Slipway'),
        "sluic": ('Mining', 'Sluicing'),
        "sod boundary wall": ('Agricultural', 'Earthen fence'),
        "sod wall": ('Agricultural', 'Earthen fence'),
        "stable": (None, 'Stable'),
        "stockyard": (None, 'Stock yard'),
        "stone wall": (None, 'Stone wall'),
        "stone wall": (None, 'Stone wall'),
        "store": (None, 'Store'),
        "structure": (None, 'Structure'),
        "tailing": ('Mining', 'Tailing'),
        "tannery": ('Industry', 'Tannery'),
        "taro": ('Botanical', 'Taro'),
        "timber dam": ('Forestry', 'Driving dam'),
        "timber mill": ('Forestry', 'Saw mill'),
        "town": (None, 'Town'),
        "track": (None, 'Track'),
        "trading": ('Commerce', 'Trading station'),
        "tramway": (None, ''),
        "tree": ('Botanical', 'Trees'),
        "trig": ('Administration', 'Trig'),
        "urupa": ('Burial', 'Urupa'),
        "village": (None, 'Village'),
        "warehouse": ('Commerce', 'Warehouse'),
        "well": (None, 'Well'),
        "wharf": ('Maritime', 'Wharf'),
        "woolshed": ('Agricultural', 'Wool shed'),
    },
}

subtype_burial = {
    "cemetery": 'Cemetery',
    "cranium": 'Cranium',
    "grave": 'Graves',
    "skull": 'Cranium',
    "urupa": 'Urupa',
}

subtype_health = {
    "building": ('Domestic', 'Building'),
    "camp": ('Domestic', 'Camp'),
    "cottage": ('Domestic', 'Cottage'),
    "dwelling": ('Domestic', 'Dwelling'),
    "gaol": ('Administration', 'Gaol'),
    "hospital": ('Community', 'Hospital'),
    "house": ('Domestic', 'House'),
    "kainga": ('Domestic', 'Kainga'),
    "logging camp": ('Forestry', 'Camp'),
    "school": ('Education', 'School'),
    "settlement": ('Domestic', 'settlement'),
    "shop": ('Commerce', 'Shop'),
    "store": ('Commerce', 'Store'),
    "town": ('Domestic', 'Town'),
    "township": ('Domestic', 'Township'),
    "village": ('Domestic', 'Village'),
}

subtype_horticulture = {
    "borrow pit": 'Borrow pits',
    "drain": 'Drainage system',
    "field": 'Field system',
    "soil": 'Modified soils',
    "stone": 'Stone piles',
}

subtype_pa = {
    "cliff pa": 'Cliff pa',
    "clifftop pa": 'Cliff pa',
    "cliff edge pa": 'Cliff pa',
    "cliff-top pa": 'Cliff pa',
    "cliff top pa": 'Cliff pa',
    "gunfighter": 'Gunfighter pa',
    "gun fighter": 'Gunfighter pa',
    "headland": 'Headland pa',
    "island": 'Island pa',
    "ridge pa": 'Ridge pa',
    "ridge peak pa": 'Ridge pa',
    "ridge top pa": 'Ridge pa',
    "ridgetop pa": 'Ridge pa',
    "ridge-top pa": 'Ridge pa',
    "river pa": 'River pa',
    "swamp": 'Swamp pa',
    "urupa": 'Pa and urupa',
}

subtype_unclass = {
    "battle": ('Traditional site', 'Battle ground'),
    "burial": ('Burial', None),
    "findspot": ('Find spot', None),
    "house": ('Domestic', 'House'),
    "kainga": ('Domestic', 'Kainga'),
    "mythological": ('Traditional site', ''),
    "not a pa": ('Not a site', 'Not a pa'),
    "not pa": ('Not a site', 'Not a pa'),
    "not pits": ('Not a site', 'Not pits'),
    "not terraces": ('Not a site', 'Not terraces'),
    "not": ('Not a site', None),
    "settlement": ('Domestic', 'Settlement'),
    "tapu": ('Traditional site', None),
    "traditional": ('Traditional site', None),
    "village": ('Domestic', 'Village'),
}

overides = {
    "burial": ('Burial', None),
    "drive dam": ('Forestry', 'Drive dam'),
    "grave": ('Burial', 'Grave'),
    "gum digging": ('Gum digging', 'Gum holes'),
    "gum hole": ('Gum digging', 'Gum holes'),
    "gumcamp": ('Gum digging', 'Camp'),
    "gumdigger": ('Gum digging', None),
    "gumhole": ('Gum digging', 'Gum holes'),
    "hotel": ('Commerce', 'Hotel'),
    "mine ": ('Mining', None),
    "miner": ('Mining', None),
    "mining": ('Mining', None),
    "prospect": ('Mining', 'Prospecting'),
}


def map_type(data):
    """Traverse the type_map dictionary and return (site_type site_subtype).

    First, search the type_map. In cases where a subtype is not given,
    search the subtype_map variable. Then process exceptions, which
    are input values for site_type which have their own
    vocabularies. Compare these aginst the appropriate subtype maps.

    Finally, iterate through the
    """

    site_type = None
    subtype = None

    for input_type in sorted(type_map.keys()):
        if input_type == data['type']:
            (site_type, subtype) = type_map[input_type]

    if not subtype:
        for item in sorted(subtype_map['short_desc']):
            if item in data['short_desc'].lower():
                subtype = subtype_map['short_desc'][item][1]
                if subtype_map['short_desc'][item][0]:
                    site_type = subtype_map['short_desc'][item][0]

    # Exceptions
    if 'Burial' in data['type']:
        site_type = 'Burial'
        for item in sorted(subtype_burial.keys()):
            if item in data['short_desc'].lower():
                subtype = subtype_burial[item]

    if "Health care" in data['type']:
        for item in sorted(subtype_health.keys()):
            if item in data['short_desc'].lower():
                subtype = subtype_health[item][1]
                if subtype_health[item][0]:
                    type = subtype_health[item][0]

    if 'Maori horticulture' in data['type']:
        site_type = 'Maori horticulture'
        for item in sorted(subtype_horticulture.keys()):
            if item in data['short_desc'].lower():
                subtype = subtype_horticulture[item]

    if 'Pa' in data['type']:
        site_type = 'Pa'
        for item in sorted(subtype_pa.keys()):
            if item in data['short_desc'].lower():
                subtype = subtype_pa[item]

    if ('Unclassified' in data['type'] or not data['type']):
        site_type = 'Unclassified'
        subtype = None
        for item in sorted(subtype_unclass.keys()):
            if item in data['short_desc'].lower():
                site_type = subtype_unclass[item][0]
                subtype = subtype_unclass[item][1]

    # Overides
    for item in sorted(overides.keys()):
        if item in data['short_desc'].lower():
            site_type = overides[item][0]
            if overides[item][1]:
                subtype = overides[item][1]

    return (site_type, subtype)


def map_period(data):
    """Trap all comma-separated values from period input. """

    result = data['period']
    periods = data['period'].split(', ')
    output = []

    for period in periods:
        if period in period_map['period'].keys():
            output.append(period_map['period'][period])

    for keyword in sorted(period_map['short_desc']):
        if (keyword in data['short_desc'].lower()):
            output.append(period_map['short_desc'][keyword])

    result = ", ".join(output)
    return result


def map_ethnicity(data):
    result = data['ethnicity']

    if data['ethnicity'] in ethnicity_map.keys():
        result = ethnicity_map[data['ethnicity']]

    for group in sorted(ethnicity_map.keys()):
        if group in data['short_desc'].lower():
            result = ethnicity_map[group]

    return result
